name: Build and Upload to Itch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      # 2. Free Space
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      # 3. DECODE LICENSE (The Fix)
      - name: Decode License
        run: |
          echo "${{ secrets.UNITY_LICENSE }}" | base64 --decode > .ulf
          
      # 4. Build
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          version: 2022.3.10f1 # Check this version matches Unity Hub!
          unityLicensingServer: .ulf # Read the file we just made

      # 5. Zip
      - name: Zip Build
        run: |
          cd build/WebGL/WebGL
          zip -r ../../../game.zip . 

      # 6. Deploy
      - name: Deploy to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: Happy # <--- CHANGE THIS
          ITCH_USER: ramenian   # <--- CHANGE THIS
          PACKAGE: game.zip
